import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/core/providers/auth-provider";

const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "@/components/ui/sonner";
import StoreProvider from "@/core/providers/store-provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`container px-0  ${inter.className}`}>
        <StoreProvider>
          <AuthProvider>
            {" "}
            <Toaster />
            {children}
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
